src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmployeRepository::class)
 */
class Employe
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Rue;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Ville;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateEmbauche;

    /**
     * @ORM\Column(type="integer")
     */
    private $Salaire;

    /**
     * @ORM\ManyToOne(targetEntity=Fonction::class, inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Fonction;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->Rue;
    }

    public function setRue(string $Rue): self
    {
        $this->Rue = $Rue;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->DateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $DateEmbauche): self
    {
        $this->DateEmbauche = $DateEmbauche;

        return $this;
    }

    public function getSalaire(): ?int
    {
        return $this->Salaire;
    }

    public function setSalaire(int $Salaire): self
    {
        $this->Salaire = $Salaire;

        return $this;
    }

    public function getFonction(): ?Fonction
    {
        return $this->Fonction;
    }

    public function setFonction(?Fonction $Fonction): self
    {
        $this->Fonction = $Fonction;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="{{ asset('assets/lib/bootstrap-4.4.1-dist/css/bootstrap.min.css') }}" />
            <link rel="stylesheet" href="{{ asset('assets/libMaya/styleMaya.css') }}" />
            <link href="{{ asset('assets/lib/font-awesome/css/font-awesome.css') }}" rel="stylesheet" />
        {% endblock %}
    </head>
    <body>
          <nav class="navbar navbar-expand-md bg-success navbar-dark fixed-top">
        <!-- Brand -->
        <a class="navbar-brand" href="#">La ferme de Maya</a>

        <!-- Toggler/collapsible Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a class="nav-link" href="http://localhost:8000/accueil/">Accueil</a>
                </li>
                {% if app.user %}
            {% if is_granted('ROLE_ADMIN') %}
                <a class="nav-link" href="{{ path('categorie')}}">Catégories</a>
                <li class="nav-item">
                    <a class="nav-link" href="http://localhost:8000/user/">Utilisateur</a>
                </li>
            </li>
            {% endif %}
        {% endif %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ path('produit_menu')}}">Produits</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Recettes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Clients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Commandes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('app_fonction')}}">fonction</a>
                </li>
                
                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Statistiques
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Fonction</a>
                        <a class="dropdown-item" href="#">Link 2</a>
                        <a class="dropdown-item" href="#">Link 3</a>
                    </div>
                </li>
                <li class="nav-item">
                                       {#    si un utilisateur existe (et est donc connecté)    #}
                    {% if app.user %}
                        <li><a class="nav-link" href="{{ path('app_logout')}}">Se déconnecter</a></li>
                    {% else %}
                        <li><a class="nav-link" href="{{ path('app_login')}}">Se connecter</a></li>
                    {% endif %}
                </li>
            </ul>
        </div>
        {% if app.user %}
            <span class="navbar-brand pull-right">{{ app.user.prenom}} {{ app.user.nom }}</span>
        {% endif %}

    </nav>
    <div class="container-fluid">
        {% block body %}{% endblock %}
    </div>
        {% block javascripts %}{% endblock %}

    </body>
</html>

templates/messages.html.twig
{% block flash_messages %}
            {% for type, messages in app.session.flashbag.all() %}
               {% for message in messages %}
                  <div class="alert alert-{{ type }} alert-dismissible" role="alert">
                     <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                     {{ message | raw }}
                  </div>
               {% endfor %}
            {% endfor %}
         {% endblock %}